### ISSUE TITLE
Sign Up error

### ISSUE THREAD

**Issue by muddlebee** [systers/macc#71]
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
    self.send_headers()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
    self.send_preamble()
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 194, in send_preamble
    'Date: %s\r\n' % format_date_time(time.time())
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

**Comment by muddlebee** [comment]
probably related to SMTP ?

**Comment by medhach** [comment]
@anweshknayak Did you solve this?

**Comment by muddlebee** [comment]
Nope. This problem I am facing  SMTP related. looks like compatibility issue ? @medhach

**Comment by mish24** [comment]
@anweshknayak I've had this kind of problem before. Nothing's wrong on your part. I suppose there's a glitch somewhere where two databases are being accessed simultaneously, hence slowing the server. I googled this "Broken pipe" issue and it's mentioned there that it's not necessary that everyone will face this issue.

**Comment by muddlebee** [comment]
@mish24 can you fix this ?

**Comment by mish24** [comment]
@anweshknayak Yup I'll take this up. Mainly the problem is that there is a place where we've created an instance and called the save() method twice by accident.

**Comment by muddlebee** [comment]
fix : use postgreSQL version 9.4+
